# Generated by Django 4.2.10 on 2026-04-13 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('pickup_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('travel_date', models.DateField()),
                ('days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('car_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any special instructions')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated estimate shown to customer', max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Admin sets final confirmed price', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('assigned_driver', models.CharField(blank=True, help_text='Driver name assigned by admin', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('from_city', models.CharField(blank=True, help_text='e.g. Kolkata', max_length=100)),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_visible', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='+91 XXXXXXXXXX', help_text='WhatsApp number displayed on contact page (with country code)', max_length=20)),
                ('address', models.TextField(default='Ma Mangala Travels, Puri, Odisha, India', help_text='Office address')),
                ('email', models.EmailField(blank=True, default='info@mamangalatravels.com', max_length=254)),
                ('tagline', models.CharField(default='Discover the Soul of Odisha', help_text='Hero section tagline', max_length=200)),
                ('about_text', models.TextField(default='Ma Mangala Travels is a trusted local travel company based in Odisha, dedicated to providing authentic and memorable travel experiences across Puri, Chilika Lake, and Bhubaneswar. We are committed to safe, comfortable, and affordable journeys.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Maruti Swift', max_length=100)),
                ('car_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV')], max_length=20)),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Rate in ₹ per km', max_digits=8)),
                ('fixed_daily_charge', models.DecimalField(decimal_places=2, help_text='Fixed charge per day in ₹', max_digits=8)),
                ('capacity', models.PositiveIntegerField(help_text='Number of passengers')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['car_type'],
            },
        ),
    ]
